### ISSUE TITLE
Can't clone private repo from github

### ISSUE THREAD

**Issue by kkolotyuk** [someteam/acha#10]
Acha doesn't want to scan my private repos. 

I installed the app locally, tried to use https clone url from github and got "Not authorized" message, tried ssh clone url from github like git@github.com:Foo/foo.git and got "Cannot add git@github.com:Foo/foo.git: java.net.URISyntaxException: Illegal character in scheme name at index 3: git@github.com:Foo/foo.git". I am sure I have full access to the repos with my ssh keys. May be problems with private key pass phrase?

The only way it works for me is to clone repo manually and then give "file:/path-to-repo" as clone URL to Acha.

**Comment by avasenin** [comment]
I've decided to add only support custom private files without passphrase. jgit doesn't support ssh-agent out-of-box and need to implement some trick to pass passphrase to identity. Let see, probably it's not needed at all.

Thanks
