### ISSUE TITLE
Slow site speed

### ISSUE THREAD

**Issue by vbauer** [someteam/acha#12]
Browser logs:
```
read-transit /api/db/ (1109713 bytes): 73.624ms
acha.min.js:938 Pushed 28186 datoms
acha.min.js:986 DB initialization: 234.714ms
```

Hardware:
* Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz 3.30 GHz
* RAM: 8 GB
* OS: Windows 7 Ultimate 64bit

Browser: Google Chrome, Version 40.0.2214.94 m

PS: Checked on http://acha-acha.co

**Comment by avasenin** [comment]
We have a task to reduce the amount of users on front page and add ability to search. I hope that some day we will do this :)

In any case @tonsky already committed a code to reduce the number of users on front page but it hasn't been deployed yet.

**Comment by avasenin** [comment]
We've added scroll appender for users pane. 

Now we show only 50 users at first and present next chunk of 20 users when users reach end of document (like Facebook or Instagram). This should significantly decrease the number of DOM elements/gravatar calls and increase site speed when the number of users > 2000+
